// Der Befehl `openvideo` auf dem Host (ADR 0029): ein erzeugtes Shellskript, das OpenVideo im Container
// (Docker/Podman) bzw. im Pod (Kubernetes) ausführt. Argumente gehen unverändert als "$@" durch – nie über
// eval oder eine zweite Shell-Auswertung. Das API-Token steht nur in api.env (0600), nie auf der Kommandozeile.
import { psq, shq } from './util.mjs';

/** Kennzeichen erzeugter Wrapper (das Setup überschreibt/entfernt nur Dateien mit dieser Zeile). */
export const WRAPPER_MARKER = 'openvideo-wrapper: generated by npm run setup';

/**
 * Umgebungsvariablen, die der Wrapper nicht in den Container reicht: Pfade und Einstellungen des Hosts
 * (Programme, Cache, Studio-Dateien) und Werte, die der Wrapper selbst setzt.
 */
export const HOST_ONLY_ENV = [
  'OPENVIDEO_API_TOKEN',
  'OPENVIDEO_BLENDER',
  'OPENVIDEO_CACHE_DIR',
  'OPENVIDEO_CHROMIUM',
  'OPENVIDEO_CONFIG_DIR',
  'OPENVIDEO_CONTAINER_IMAGE',
  'OPENVIDEO_DOCKER',
  'OPENVIDEO_ESPEAK',
  'OPENVIDEO_FFMPEG',
  'OPENVIDEO_FFPROBE',
  'OPENVIDEO_PIPER',
  'OPENVIDEO_PIPER_MODEL',
  'OPENVIDEO_PUBLIC_URL',
  'OPENVIDEO_RUNTIME',
  'OPENVIDEO_RUNTIME_INFO',
  'OPENVIDEO_STUDIO_DIR',
  'OPENVIDEO_VERSION',
  'OPENVIDEO_WHISPER',
  'OPENVIDEO_WHISPER_MODEL',
  'OPENVIDEO_WORKSPACE',
];

/** Gemeinsamer Anfang beider POSIX-Wrapper. */
function header(runtime) {
  return `#!/bin/sh
# openvideo – runs OpenVideo with the runtime "${runtime}" (ADR 0029).
# ${WRAPPER_MARKER}. Do not edit: run \`npm run setup\` in the OpenVideo checkout again.
set -eu
`;
}

/**
 * POSIX-Wrapper für Docker und Podman.
 *
 * - `run --rm -i` (plus `-t` bei Terminal, nie für `mcp`), `--pull never` (nur das lokal gebaute Image),
 *   `--security-opt no-new-privileges`, `--cap-drop ALL`, kein `--privileged`.
 * - Aktueller Ordner unter demselben absoluten Pfad eingehängt und Arbeitsverzeichnis; ebenso `--workspace`,
 *   `--project` und `OPENVIDEO_WORKSPACE`, wenn sie außerhalb liegen. So stimmen Pfade in Ausgaben und
 *   MCP-Antworten auf dem Host.
 * - Nutzer-ID des Aufrufers (Docker `--user`, Podman rootless `--userns=keep-id`): Dateien gehören dem Nutzer.
 * - Benanntes Volume `openvideo-cache-<uid>` als Cache (je Nutzer, kein geteilter Cache zwischen Nutzern), `OPENVIDEO_*` des Hosts gehen durch (außer {@link HOST_ONLY_ENV}).
 * - `serve`/`dev`/`studio`: Port nur auf 127.0.0.1 veröffentlicht, Server im Container auf 0.0.0.0 mit
 *   Token aus `--env-file`, Links über `OPENVIDEO_PUBLIC_URL`.
 */
export function containerWrapper({ engine, enginePath, image, envFile, volume = 'openvideo-cache', rootless = false, gpu, runtimeInfo, pollMs }) {
  const gpuArgs = gpu === 'docker' ? 'set -- "$@" --gpus all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,graphics' : gpu === 'cdi' ? 'set -- "$@" --device nvidia.com/gpu=all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,graphics' : ':';
  return `${header(engine)}
OV_ENGINE=${shq(enginePath)}
OV_IMAGE=${shq(image)}
OV_ENV_FILE=${shq(envFile)}
OV_VOLUME=${shq(volume)}
OV_ROOTLESS=${shq(rootless ? '1' : '0')}
OV_RUNTIME_INFO=${shq(runtimeInfo)}
OV_POLL_MS=${shq(pollMs ?? '')}

fail() { echo "openvideo: $*" >&2; exit 2; }
abspath() { case "$1" in /*) printf '%s' "$1" ;; *) printf '%s/%s' "$cwd" "$1" ;; esac; }
inside() { case "$1/" in "$cwd"/*) return 0 ;; *) return 1 ;; esac; }

cwd="$(pwd -P)"
cmd="\${1:-}"

# Werte aus den Argumenten lesen, ohne sie zu verändern.
ws=''; proj=''; port='7788'; has_host=0; prev=''
for a in "$@"; do
  case "$prev" in
    --workspace) ws="$a" ;;
    --project) proj="$a" ;;
    --port) port="$a" ;;
  esac
  case "$a" in
    --workspace=*) ws="\${a#--workspace=}" ;;
    --project=*) proj="\${a#--project=}" ;;
    --port=*) port="\${a#--port=}" ;;
    --host|--host=*) has_host=1 ;;
  esac
  prev="$a"
done
case "$port" in ''|*[!0-9]*) fail "--port must be a number" ;; esac

server=0
case "$cmd" in serve|dev|studio) server=1 ;; esac

n=$#
set -- "$@" run --rm -i --pull never --security-opt no-new-privileges --cap-drop ALL --shm-size 512m
if [ "$cmd" != mcp ] && [ -t 0 ] && [ -t 1 ]; then set -- "$@" -t; fi
if [ "$OV_ROOTLESS" = 1 ]; then set -- "$@" --userns=keep-id; fi
set -- "$@" --user "$(id -u):$(id -g)"
# SELinux (z. B. Fedora): Bind-Mounts ohne Umetikettieren des Nutzerordners lesbar machen.
if [ -r /sys/fs/selinux/enforce ] && [ "$(cat /sys/fs/selinux/enforce)" = 1 ]; then set -- "$@" --security-opt label=disable; fi

case "$cwd" in *:*) fail "the current folder contains ':' and cannot be mounted: $cwd" ;; esac
# Cache je Nutzer (openvideo-cache-<uid>): Nutzer eines Docker-Hosts teilen keine Cache-Einträge.
set -- "$@" -v "$cwd:$cwd" -w "$cwd" -v "$OV_VOLUME-$(id -u):/var/cache/openvideo"
if [ -n "$ws" ]; then
  ws="$(abspath "$ws")"
  mkdir -p "$ws"
  ws="$(cd "$ws" && pwd -P)"
  case "$ws" in *:*) fail "--workspace contains ':' and cannot be mounted: $ws" ;; esac
  inside "$ws" || set -- "$@" -v "$ws:$ws"
fi
if [ -n "$proj" ]; then
  proj="$(abspath "$proj")"
  [ -d "$proj" ] || fail "project folder not found: $proj"
  proj="$(cd "$proj" && pwd -P)"
  case "$proj" in *:*) fail "--project contains ':' and cannot be mounted: $proj" ;; esac
  inside "$proj" || set -- "$@" -v "$proj:$proj"
fi
if [ -n "\${OPENVIDEO_WORKSPACE:-}" ]; then
  envws="$(abspath "$OPENVIDEO_WORKSPACE")"
  mkdir -p "$envws"
  envws="$(cd "$envws" && pwd -P)"
  case "$envws" in *:*) fail "OPENVIDEO_WORKSPACE contains ':' and cannot be mounted: $envws" ;; esac
  inside "$envws" || set -- "$@" -v "$envws:$envws"
  set -- "$@" -e "OPENVIDEO_WORKSPACE=$envws"
fi

# OPENVIDEO_* des Hosts durchreichen (nur die Namen; die Werte liest ${engine} aus der Umgebung).
for name in $(env | sed -n 's/^\\(OPENVIDEO_[A-Za-z0-9_]*\\)=.*/\\1/p'); do
  case "$name" in
    ${HOST_ONLY_ENV.join('|')}) ;;
    *) set -- "$@" -e "$name" ;;
  esac
done
set -- "$@" -e "OPENVIDEO_RUNTIME_INFO=$OV_RUNTIME_INFO"
if [ -n "$OV_POLL_MS" ] && [ -z "\${OPENVIDEO_WATCH_POLL_MS:-}" ]; then set -- "$@" -e "OPENVIDEO_WATCH_POLL_MS=$OV_POLL_MS"; fi
${gpuArgs}

if [ "$server" = 1 ]; then
  [ -r "$OV_ENV_FILE" ] || fail "API token file $OV_ENV_FILE is missing; run npm run setup in the OpenVideo checkout again"
  set -- "$@" -p "127.0.0.1:$port:$port" --env-file "$OV_ENV_FILE" -e "OPENVIDEO_PUBLIC_URL=http://127.0.0.1:$port"
  if [ "$cmd" = serve ]; then
    token="$(sed -n 's/^OPENVIDEO_API_TOKEN=//p' "$OV_ENV_FILE")"
    echo "openvideo: Studio with API token: http://127.0.0.1:$port/#token=$token" >&2
  fi
fi
set -- "$@" "$OV_IMAGE"

# Die Argumente des Aufrufs ans Ende rotieren – unverändert.
i=0
while [ "$i" -lt "$n" ]; do set -- "$@" "$1"; shift; i=$((i + 1)); done
if [ "$server" = 1 ]; then
  [ "$has_host" = 1 ] || set -- "$@" --host 0.0.0.0
  set -- "$@" --no-open
fi
exec "$OV_ENGINE" "$@"
`;
}

/**
 * POSIX-Wrapper für Kubernetes. Befehle laufen per `kubectl exec` im Pod `deploy/openvideo`:
 *
 * - `mcp`: stdio über `kubectl exec -i`, Workspace ist das PVC (`--workspace /workspace`).
 * - `serve`/`studio`: `kubectl port-forward` auf 127.0.0.1:7788; die Studio-URL trägt das Token (`#token=`).
 * - `doctor`, `templates`, `--help`, `--version`: direkt im Pod.
 * - `dev`, `worker`, `coordinator`: nicht über diesen Wrapper (Meldung, Exit-Code 2).
 * - alle übrigen (`create`, `validate`, `render`, `render-frame`, `op` …): Der aktuelle Ordner wird in den
 *   Pod gespiegelt (tar über exec, ohne node_modules/.git/out/.openvideo), der Befehl läuft dort, und alle
 *   Dateien, die er neu schreibt oder ändert, kommen zurück in denselben relativen Pfad.
 */
export function kubernetesWrapper({ kubectlPath, context, namespace, envFile, port = 7788 }) {
  return `${header('kubernetes')}
OV_KUBECTL=${shq(kubectlPath)}
OV_CONTEXT=${shq(context)}
OV_NAMESPACE=${shq(namespace)}
OV_ENV_FILE=${shq(envFile)}
OV_PORT=${shq(String(port))}
OV_TARGET='deploy/openvideo'
OV_CONTAINER='openvideo'

fail() { echo "openvideo: $*" >&2; exit 2; }
k() { "$OV_KUBECTL" --context "$OV_CONTEXT" -n "$OV_NAMESPACE" "$@"; }

cwd="$(pwd -P)"
cmd="\${1:-}"
tty=''
if [ "$cmd" != mcp ] && [ -t 0 ] && [ -t 1 ]; then tty='-t'; fi

case "$cmd" in
  mcp)
    # Der Workspace ist das PVC im Pod; Ordner des Hosts gibt es dort nicht.
    n=$#; i=0; skip=0; dropped=0
    while [ "$i" -lt "$n" ]; do
      a="$1"; shift; i=$((i + 1))
      if [ "$skip" = 1 ]; then skip=0; continue; fi
      case "$a" in
        --workspace|--project) skip=1; dropped=1; continue ;;
        --workspace=*|--project=*) dropped=1; continue ;;
      esac
      set -- "$@" "$a"
    done
    if [ "$dropped" = 1 ]; then echo "openvideo: runtime kubernetes: the MCP server uses the workspace in the pod (/workspace); --workspace/--project are ignored." >&2; fi
    exec "$OV_KUBECTL" --context "$OV_CONTEXT" -n "$OV_NAMESPACE" exec -i "$OV_TARGET" -c "$OV_CONTAINER" -- openvideo "$@" --workspace /workspace
    ;;
  serve|studio)
    [ -r "$OV_ENV_FILE" ] || fail "API token file $OV_ENV_FILE is missing; run npm run setup in the OpenVideo checkout again"
    token="$(sed -n 's/^OPENVIDEO_API_TOKEN=//p' "$OV_ENV_FILE")"
    echo "OpenVideo Studio (runtime kubernetes, workspace in the pod): http://127.0.0.1:$OV_PORT/#token=$token" >&2
    echo "Agent API: http://127.0.0.1:$OV_PORT/v1/operations (Authorization: Bearer <token>). Stop with Ctrl+C." >&2
    exec "$OV_KUBECTL" --context "$OV_CONTEXT" -n "$OV_NAMESPACE" port-forward --address 127.0.0.1 svc/openvideo "$OV_PORT:7788"
    ;;
  dev)
    fail "runtime kubernetes: 'dev' watches files on this computer and is not available. Use 'openvideo studio' (workspace in the pod) or set up the docker/podman runtime."
    ;;
  worker|coordinator)
    fail "runtime kubernetes: '$cmd' is not started through this wrapper; use deploy/k8s/overlays/production for render workers."
    ;;
  ''|-h|--help|help|doctor|templates|--version|-v)
    exec "$OV_KUBECTL" --context "$OV_CONTEXT" -n "$OV_NAMESPACE" exec -i $tty "$OV_TARGET" -c "$OV_CONTAINER" -- openvideo "$@"
    ;;
esac

# Befehle mit Dateien: aktuellen Ordner in den Pod spiegeln, dort ausführen, Ergebnisse zurückholen.
[ "$cwd" != / ] && [ "$cwd" != "\${HOME:-}" ] || fail "run openvideo in a project folder, not in $cwd (runtime kubernetes copies the current folder into the pod)"
id="$(printf '%s' "$cwd" | cksum | cut -d ' ' -f 1)"
remote="/var/cache/openvideo/host/$id"

# op ohne --workspace/--project arbeitet im Workspace des Pods (wie MCP und Studio).
extra=0
if [ "$cmd" = op ]; then
  extra=1
  for a in "$@"; do
    case "$a" in --workspace|--workspace=*|--project|--project=*) extra=0 ;; esac
  done
fi

COPYFILE_DISABLE=1 tar -C "$cwd" -cf - --exclude=node_modules --exclude=.git --exclude=out --exclude=.openvideo --exclude=.openvideo-workspace . \\
  | k exec -i "$OV_TARGET" -c "$OV_CONTAINER" -- sh -c 'set -e; mkdir -p "$1"; find "$1" -mindepth 1 -maxdepth 1 ! -name .openvideo -exec rm -rf {} +; tar -x -m -f - -C "$1" --no-same-owner --no-same-permissions --warning=no-unknown-keyword; touch "$1/.openvideo-sync"' sh "$remote" \\
  || fail "could not copy $cwd into the pod (kubectl exec failed; is deploy/openvideo running? kubectl --context $OV_CONTEXT -n $OV_NAMESPACE get pods)"

set +e
if [ "$extra" = 1 ]; then
  k exec -i $tty "$OV_TARGET" -c "$OV_CONTAINER" -- sh -c 'cd "$1" && shift && exec openvideo "$@"' sh "$remote" "$@" --workspace /workspace
else
  k exec -i $tty "$OV_TARGET" -c "$OV_CONTAINER" -- sh -c 'cd "$1" && shift && exec openvideo "$@"' sh "$remote" "$@"
fi
rc=$?
set -e

k exec "$OV_TARGET" -c "$OV_CONTAINER" -- sh -c 'cd "$1" && find . -newer .openvideo-sync -type f ! -name .openvideo-sync ! -path "*/.openvideo/*" -print0 | tar -c --null -T - -f -' sh "$remote" \\
  | tar -x -f - -C "$cwd" --no-same-owner \\
  || echo "openvideo: could not copy the results back from the pod ($remote)." >&2
exit "$rc"
`;
}

/**
 * PowerShell-Wrapper für Windows (Docker/Podman). Ordner unter /work, `--workspace`/`--project` außerhalb
 * davon unter /mnt/workspace bzw. /mnt/project; Argumente gehen als Array durch (`& $engine @a`).
 */
export function powershellWrapper({ engine, enginePath, image, envFile, volume = 'openvideo-cache', runtimeInfo }) {
  return `# openvideo – runs OpenVideo with the runtime "${engine}" (ADR 0029).
# ${WRAPPER_MARKER}. Do not edit: run \`npm run setup\` in the OpenVideo checkout again.
$ErrorActionPreference = 'Stop'
$engine = ${psq(enginePath)}
$image = ${psq(image)}
$envFile = ${psq(envFile)}
$hostOnly = @(${HOST_ONLY_ENV.map((n) => psq(n)).join(', ')})
$cmd = if ($args.Count -gt 0) { [string]$args[0] } else { '' }
$cwd = (Get-Location).ProviderPath
$server = @('serve', 'dev', 'studio') -contains $cmd
$a = @('run', '--rm', '-i', '--pull', 'never', '--security-opt', 'no-new-privileges', '--cap-drop', 'ALL', '--shm-size', '512m')
if ($cmd -ne 'mcp' -and -not [Console]::IsInputRedirected -and -not [Console]::IsOutputRedirected) { $a += '-t' }
$a += @('-v', "\${cwd}:/work", '-w', '/work', '-v', ${psq(`${volume}:/var/cache/openvideo`)})
$user = @()
$port = '7788'
$hasHost = $false
for ($i = 0; $i -lt $args.Count; $i++) {
  $v = [string]$args[$i]
  if (($v -eq '--workspace' -or $v -eq '--project') -and $i + 1 -lt $args.Count) {
    $dir = [System.IO.Path]::GetFullPath((Join-Path $cwd ([string]$args[$i + 1])))
    if ($v -eq '--workspace') { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $mount = if ($v -eq '--workspace') { '/mnt/workspace' } else { '/mnt/project' }
    $a += @('-v', "\${dir}:\${mount}")
    $user += @($v, $mount)
    $i++
    continue
  }
  if ($v -eq '--port' -and $i + 1 -lt $args.Count) { $port = [string]$args[$i + 1] }
  if ($v -eq '--host' -or $v.StartsWith('--host=')) { $hasHost = $true }
  $user += $v
}
if ($port -notmatch '^[0-9]+$') { Write-Error 'openvideo: --port must be a number'; exit 2 }
Get-ChildItem Env: | Where-Object { $_.Name -like 'OPENVIDEO_*' -and $hostOnly -notcontains $_.Name } | ForEach-Object { $a += @('-e', $_.Name) }
$a += @('-e', ${psq(`OPENVIDEO_RUNTIME_INFO=${runtimeInfo}`)})
if (-not $env:OPENVIDEO_WATCH_POLL_MS) { $a += @('-e', 'OPENVIDEO_WATCH_POLL_MS=1000') }
if ($server) {
  if (-not (Test-Path $envFile)) { Write-Error "openvideo: API token file $envFile is missing; run npm run setup again"; exit 2 }
  $a += @('-p', "127.0.0.1:\${port}:\${port}", '--env-file', $envFile, '-e', "OPENVIDEO_PUBLIC_URL=http://127.0.0.1:\${port}")
  if ($cmd -eq 'serve') {
    $token = (Get-Content $envFile | Where-Object { $_ -like 'OPENVIDEO_API_TOKEN=*' }) -replace '^OPENVIDEO_API_TOKEN=', ''
    [Console]::Error.WriteLine("openvideo: Studio with API token: http://127.0.0.1:\${port}/#token=$token")
  }
}
$a += $image
$a += $user
if ($server) {
  if (-not $hasHost) { $a += @('--host', '0.0.0.0') }
  $a += '--no-open'
}
& $engine @a
exit $LASTEXITCODE
`;
}

/** `openvideo.cmd` für cmd.exe und MCP-Clients unter Windows: ruft den PowerShell-Wrapper auf. */
export function cmdWrapper() {
  return `@echo off\r\nrem ${WRAPPER_MARKER}. Do not edit: run npm run setup again.\r\npowershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0openvideo.ps1" %*\r\nexit /b %ERRORLEVEL%\r\n`;
}
