#!/usr/bin/env node
// Lizenzinventar (FR-88, NFR-6): erzeugt licenses.json, THIRD_PARTY_NOTICES.md und eine
// CycloneDX-SBOM (sbom.cdx.json) für alle Laufzeit-Abhängigkeiten. Bricht mit Exit-Code 1 ab,
// wenn eine Laufzeit-Abhängigkeit keine erlaubte OSI-Lizenz hat.
//
// Aufruf: node scripts/licenses.mjs [--check]   (--check schreibt nichts, prüft nur)
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');

/** OSI-anerkannte Lizenzen, die als Laufzeit-Abhängigkeit erlaubt sind. */
const ALLOWED = new Set(['MIT', 'MIT-0', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC', '0BSD', 'BlueOak-1.0.0', 'MPL-2.0', 'Zlib', 'Python-2.0', 'Unicode-3.0', 'CC0-1.0', 'Unlicense']);

/** Wertet einfache SPDX-Ausdrücke aus: OR = eine erlaubte genügt, AND = alle nötig. */
function allowed(expr) {
  const clean = expr.replace(/[()]/g, ' ').trim();
  if (clean.includes(' OR ')) return clean.split(' OR ').some((p) => allowed(p.trim()));
  if (clean.includes(' AND ')) return clean.split(' AND ').every((p) => allowed(p.trim()));
  return ALLOWED.has(clean);
}

const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
const entries = [];
const problems = [];
for (const [path, meta] of Object.entries(lock.packages)) {
  if (path === '' || meta.dev === true || meta.link === true || !path.includes('node_modules/')) continue;
  const dir = join(root, path);
  if (!existsSync(join(dir, 'package.json'))) continue;
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  let license = typeof pkg.license === 'string' ? pkg.license : typeof pkg.license?.type === 'string' ? pkg.license.type : Array.isArray(pkg.licenses) ? pkg.licenses.map((l) => l.type).join(' OR ') : meta.license ?? 'UNKNOWN';
  const licenseFile = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  const text = licenseFile !== undefined ? readFileSync(join(dir, licenseFile), 'utf8') : '';
  const name = pkg.name ?? path.split('node_modules/').pop();
  const entry = { name, version: pkg.version, license, repository: typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url ?? '', path, licenseText: text };
  if (!allowed(license)) problems.push(`${name}@${pkg.version}: ${license}`);
  entries.push(entry);
}
entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : a.version < b.version ? -1 : 1));

// Gebündelte Nicht-Code-Inhalte und externe Werkzeuge (nicht gebündelt) für Transparenz.
const bundledAssets = [
  { name: 'Inter', version: '4.1', license: 'OFL-1.1', path: 'packages/fonts/assets/inter' },
  { name: 'JetBrains Mono', version: '2.304', license: 'OFL-1.1', path: 'packages/fonts/assets/jetbrains-mono' },
  { name: 'Noto Color Emoji', version: '2026-09-24', license: 'OFL-1.1', path: 'packages/fonts/assets/noto-color-emoji' },
  { name: 'CanvasKit (Skia)', version: '0.42.0', license: 'BSD-3-Clause', path: 'node_modules/canvaskit-wasm' },
];
const externalTools = [
  { name: 'FFmpeg', license: 'LGPL-2.1-or-later or GPL-2.0-or-later (depends on build)', note: 'External process, never bundled. The render manifest records the exact build license and codec licenses.' },
  { name: 'Chromium (via Playwright)', license: 'BSD-3-Clause and others', note: 'Downloaded by Playwright or provided by the container image; not bundled in npm packages.' },
  { name: 'Blender', license: 'GPL-2.0-or-later', note: 'Optional external process for blender nodes; not bundled.' },
  { name: 'Piper, espeak-ng, whisper.cpp', license: 'MIT / GPL-3.0 / MIT', note: 'Optional external speech engines; not bundled.' },
];

if (problems.length > 0) {
  console.error('Nicht erlaubte Lizenzen in Laufzeit-Abhängigkeiten:\n' + problems.map((p) => `  - ${p}`).join('\n'));
  process.exit(1);
}

if (!checkOnly) {
  writeFileSync(join(root, 'licenses.json'), JSON.stringify({ generated: 'scripts/licenses.mjs', policy: [...ALLOWED], dependencies: entries.map(({ licenseText, ...e }) => e), bundledAssets, externalTools }, null, 2) + '\n');
  const notices = ['# Third-Party Notices', '', 'OpenVideo (Apache-2.0) uses the following third-party software at runtime.', 'Generated by `node scripts/licenses.mjs`. Do not edit by hand.', ''];
  notices.push('## Bundled assets', '', ...bundledAssets.map((a) => `- ${a.name} ${a.version} – ${a.license} (${a.path})`), '');
  notices.push('## External tools (not bundled)', '', ...externalTools.map((t) => `- ${t.name} – ${t.license}. ${t.note}`), '');
  notices.push('## npm dependencies', '');
  for (const e of entries) {
    notices.push(`### ${e.name} ${e.version}`, '', `License: ${e.license}${e.repository ? `  \nSource: ${e.repository}` : ''}`, '');
    if (e.licenseText.trim() !== '') notices.push('```text', e.licenseText.trim(), '```', '');
  }
  writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), notices.join('\n'));
  const rootPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const sbom = {
    bomFormat: 'CycloneDX',
    specVersion: '1.5',
    serialNumber: `urn:uuid:${createHash('sha256').update(JSON.stringify(entries.map((e) => [e.name, e.version]))).digest('hex').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12}).*$/, '$1-$2-$3-$4-$5')}`,
    version: 1,
    metadata: { component: { type: 'application', name: rootPkg.name, version: rootPkg.version, licenses: [{ license: { id: 'Apache-2.0' } }] } },
    components: entries.map((e) => ({ type: 'library', name: e.name, version: e.version, purl: `pkg:npm/${e.name.replace('@', '%40')}@${e.version}`, licenses: [{ expression: e.license }] })),
  };
  writeFileSync(join(root, 'sbom.cdx.json'), JSON.stringify(sbom, null, 2) + '\n');
}
console.log(`Lizenzprüfung bestanden: ${entries.length} Laufzeit-Pakete, alle mit erlaubter Lizenz.`);
